/// Flutter icons Emoticons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Emoticons
///      fonts:
///       - asset: fonts/Emoticons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Emoticons {
  Emoticons._();

  static const _kFontFam = 'Emoticons';

  static const IconData tired = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData surprise = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData smile_wink = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData smile = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData smile_beam = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData sad_tear = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData sad_cry = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData meh_rolling_eyes = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData meh = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData meh_blank = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData laugh_wink = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData laugh_squint = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData laugh = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData laugh_beam = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData kiss_wink_heart = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData kiss = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData kiss_beam = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData grin_wink = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData grin_tongue_wink = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData grin_tongue_squint = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData grin_tongue = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData grin_tears = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData grin_stars = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData grin_squint_tears = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData grin_squint = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData grin = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData grin_hearts = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData grin_beam_sweat = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData grin_beam = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData grimace = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData frown = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData frown_open = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData flushed = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData dizzy = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData angry = const IconData(0xe822, fontFamily: _kFontFam);
}
